export const SERVER_CONFIG = {
  name: "Clasher Network",
  ip: "play.clashernetwork.fun",
  port: "8000",
  version: "1.21.x",
  maxPlayers: 500,
  discord: "https://discord.gg/clashernetwork",
  description: "Build your story. Explore a world shaped by its players.",
  editions: ["Java", "Bedrock"] as const,
  accounts: "Premium and cracked",
  features: [
    { icon: "Sword", label: "Survival", description: "Classic survival with real stakes" },
    { icon: "Globe", label: "Custom World", description: "Hand-crafted terrain and biomes" },
    { icon: "Hammer", label: "Player Builds", description: "Build anything, claim everything" },
    { icon: "Calendar", label: "Events", description: "Weekly tournaments and challenges" },
    { icon: "Shield", label: "Active Staff", description: "Moderation around the clock" },
    { icon: "Users", label: "Community", description: "Friendly players from everywhere" },
  ],
  rules: {
    general: [
      "Treat all players with respect — no harassment, bullying, or discrimination.",
      "Follow staff instructions at all times.",
      "No impersonating staff members or other players.",
      "Keep conversations appropriate for all ages.",
      "Report issues through the proper channels on Discord.",
    ],
    gameplay: [
      "No cheating, hacking, or using exploits of any kind.",
      "No X-ray, fly hacks, kill aura, or auto-clickers.",
      "No abusing game-breaking bugs — report them instead.",
      "PvP is allowed only in designated areas unless mutually agreed upon.",
      "No AFK machines that impact server performance.",
    ],
    building: [
      "No griefing or destroying other players' builds.",
      "No stealing from other players' chests or storage.",
      "No inappropriate, offensive, or NSFW builds.",
      "Claim your land to protect your builds.",
      "Do not build within 100 blocks of another player's base without permission.",
    ],
    chat: [
      "No spamming, flooding, or excessive caps in chat.",
      "No advertising other servers or services.",
      "No sharing personal information in public chat.",
      "Keep political and religious debates out of chat.",
      "English is the primary language in global chat.",
    ],
  },
} as const;
